# -*- coding: utf-8 -*-
"""履歷自動產生器

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCM9vUowAus01BCI4KXq1_hFriDvsLAP
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import gradio as gr

!pip install gradio
!pip install openai

import os
from google.colab import userdata

api_key = userdata.get('履歷生成器')
model = "meta-llama/llama-4-maverick-17b-128e-instruct"
base_url="https://api.groq.com/openai/v1"

os.environ['OPENAI_API_KEY']=api_key

title = "自傳美化產生器"

system = "你是一位中文地區負責履歷撰寫的專業經理人，撰寫出台灣繁體中文自傳，是根據提供的應徵職位和個人經歷，產出履歷自傳、自我核心價值以熱忱和負責為主、工作技能為公司創造多少價值，強調專業技能、工作事項、以及常見職責與績效，語氣專業沉穩。針對應徵職位，提供該職位可能的工作職責和可量化的績效指標，並結合個人經歷來撰寫自傳。請用台灣人習慣的中文來書寫不要出現太多英文約略500字。始終以繁體中文回應，無論字數有多少"

description = "請根據提供的應徵職位和個人經歷，產出該職位常見職責與績效的履歷"

from openai import OpenAI

client = OpenAI(
    base_url = base_url
)
def mychatbot(position, experience):# 初始化 messages，確保每次生成都是新的對話
    messages = [{"role":"system", "content":system}]
    user_prompt = f"應徵職位：{position}\n個人經歷：{experience}\n請根據這些資訊，產出該職位常見職責與可量化績效的履歷亮點，並將我的個人經歷融入其中。"
    messages.append({"role": "user", "content": user_prompt})
    chat_completion =client.chat.completions.create(
        messages=messages,
        model=model,
        temperature=0.7, # 增加 temperature 可以讓回應更多樣
        max_tokens=1000# 增加 max_tokens 以獲得更長的履歷內容
    )
    reply = chat_completion.choices[0].message.content
    return reply

iface = gr.Interface(
    mychatbot,
    inputs=[
        gr.Textbox(lines=1, label="應徵職位 (例如：資深軟體工程師)", placeholder="請輸入您想應徵的職位"),
        gr.Textbox(lines=7, label="您的個人經歷 (例如：5年軟體開發經驗，熟悉Python/Java，負責過大型系統架構設計)", placeholder="請輸入您的工作經驗、技能、學歷等，越詳細越好")
    ],
    outputs="text",
    title=title,
    description=description
)

iface.launch(share=True, debug=True)